all:
	$(MAKE) -C data_channel_fifo
	$(MAKE) -C eth_ip
	$(MAKE) -C trig_latency
	$(MAKE) -C mac_fifo_axi4
clean:
	$(MAKE) -C data_channel_fifo clean
	$(MAKE) -C eth_ip clean
	$(MAKE) -C trig_latency clean
	$(MAKE) -C mac_fifo_axi4 clean
