git add  -v Firmware_GCU1F3/src/*
git add  -v Firmware_GCU1F3/externals/*
git add  -v Firmware_GCU1F3/uhal_py/*
git add  -v Firmware_GCU1F3/BEC/*
git add  -v Firmware_GCU1F3/README.md
git add  -v Firmware_GCU1F3/change_delay.tcl
git add  -v Firmware_GCU1F3/InitGCU.sh
git add  -v Firmware_GCU1F3/Regen_IPBUS_MASTER.sh
git add  -v Firmware_GCU1F3/create_bitstream.tcl
git add  -v Firmware_GCU1F3/Makefile
git add  -v gcu1f3/*
git add  -v Java_Utils/*
git add  -v README.txt
git add  -v README_GCU.txt
git add  -v GitAdd.sh
