# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-6082-chap2/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k325tffg900-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      ./.Xil/Vivado-6082-chap2/realtime/tri_mode_ethernet_mac_0_stub.v
      ./.Xil/Vivado-6082-chap2/realtime/mac_fifo_axi4_stub.v
      ./.Xil/Vivado-6082-chap2/realtime/data_channel_fifo_stub.v
      ./.Xil/Vivado-6082-chap2/realtime/trig_latency_fifo_stub.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/ADU_top.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/ADC/adc_top.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/ADC/adc_config.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/ADC/iserdes_iodelay/DDR_8TO1_16CHAN_RX_GCU.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/ADC/iserdes_iodelay/RESOURCE_SHARING_CONTROL.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/dac_pll_config/pll_config.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/dac_pll_config/dac_config.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/element/Flag_CrossDomain.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/element/Signal_CrossDomain.v
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/element/SimpleSPIMaster.v
    }
      rt::read_vhdl -lib usrDefLib {
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_package.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_fabric_sel.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_trans_decl.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_ipaddr_block.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rarp_block.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_arp.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_payload.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_ping.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_resend.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_status.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_status_buffer.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_byte_sum.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_do_rx_reset.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_packet_parser.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_mux.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_buffer_selector.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_shim.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_rx.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_tx.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxtransactor_if_simple.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_tx_mux.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_txtransactor_if_simple.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_clock_crossing_if.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_if_flat.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/trans_arb.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_if.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_sm.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_cfg.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_ctrl.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_shim.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_types.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ctrlreg_v.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_v.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ram.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/externals/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_peephole_ram.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_utils/payload.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_utils/ipbus_subsys.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_utils/ipbus_decode_gcu1f3.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_utils/ipbus_debug.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/afifo.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/l1_cache.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/fifomem.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/gray2bin.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/fifo.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/edge_detect.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/GCU_utils.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/funnel.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/ipbus_daq.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/wptr_full.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_daq/rptr_empty.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_dspsim/ipbus_dspIDMAMEMORY.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_dspsim/ipbus_dsp_slave.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_dspsim/ipbus_dsp_simulator.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_dsp_interface/ipbus_dsp_iface_slave.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_dsp_interface/DSP_control.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_dsp_interface/dsp_iface.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_dsp_loader/ipbus_dsp_loader_slave.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_dsp_loader/dsp_loader_fifo.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_dsp_loader/dsp_loader.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_trigger_manager/ipbus_trigger_manager.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_test/ipbus_memblk.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_test/ipbus_test.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_test/ipbus_counter.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_utils/ipbus_fw_data.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_adu_manager/ipbus_adu_manager.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_data_assembly/ipbus_data_assembly.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/ipbus_gpio/ipbus_gpio.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/stop_fsm.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/ttc_encoder.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/start_fsm_cont.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/ttc_trg_time.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/error_counter.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/system_clocks.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/GCU_1588_ptp.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/BrdCommandEncoder.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/ttctx_delay_calibration.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/cdr_clocks.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/bmc_generator.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/chb_shift_ctrl.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/cdr2a_b_clk.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/long_frame_maker.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/TTC_register_stack.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/top_level_cont.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/GCU_utils.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/chb_traffic_light.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/command_vector_generator.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/ttc_decoder_core.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/addressed_command_decoder.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/TTCtestpack.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/TTC_hamming_decoder_alme.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/command_vector_receiver.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/broadcast_frame_maker.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/GCUpack.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/synch/BrdCommandDecoder.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/adu_top_wrapper.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/tsinghua/adu_top/src/dac_pll_config/dac_config_wrapper.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_reset_sync.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_clk_wiz.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_config_vector_sm.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_support.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_sync_block.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_tx_client_fifo.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_axi_mux.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_rx_client_fifo.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_axi_pipe.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_ten_100_1g_eth_fifo.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_resets.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_axi_pat_gen.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_address_swap.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_clocks.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_fifo_block.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_bram_tdp.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_basic_pat_gen.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_axi_pat_check.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/eth_mac/tri_mode_ethernet_mac_0_support_resets.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/sychronizer.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/kcpsm6.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/components.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/delay_manager.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/clk_wiz.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/baudrate_gen.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/shaper.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/clock_manager.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/clock_div_2.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/uart_tx6.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/top_gcu1f3.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/gray_counter.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/mcp_block.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/network_interface.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/bin2gray.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/picoblaze_top.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/slow_clock_pulse.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/global_wire_package.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/utils_package.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/uart_rx6.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/user/clk_manager.vhd
      /home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/picoblaze/asm/rom.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-6082-chap2/realtime/top_gcu1f3_synth.xdc
    rt::sdcChecksum
    set rt::top top_gcu1f3
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-6082-chap2/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-6082-chap2/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
