# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo.xci
# IP: The module: 'channel_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'channel_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'channel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'channel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo.xci
# IP: The module: 'channel_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'channel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'channel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'channel_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
