set_property SRC_FILE_INFO {cfile:/home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo/channel_fifo_in_context.xdc rfile:../../../../fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo/channel_fifo_in_context.xdc id:1 order:EARLY scoped_inst:{network_interface_i/payload_1/ipbus_subsys_i/gen_dsp[0].dspiface/dsp_cntrl/channel_fifo_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo/channel_fifo_in_context.xdc rfile:../../../../fifo_prj/fifo_prj.srcs/sources_1/ip/channel_fifo/channel_fifo/channel_fifo_in_context.xdc id:2 order:EARLY scoped_inst:{network_interface_i/payload_1/ipbus_subsys_i/gen_dsp[1].dspiface/dsp_cntrl/channel_fifo_i}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/ip_cores/mac_fifo_axi4/mac_fifo_axi4/mac_fifo_axi4_in_context.xdc rfile:../../../src/ip_cores/mac_fifo_axi4/mac_fifo_axi4/mac_fifo_axi4_in_context.xdc id:3 order:EARLY scoped_inst:network_interface_i/mac_fifo_axi4_1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bini/GARFIELD_MOBO/Firmware_GCU1F3/src/ip_cores/eth_ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0_in_context.xdc rfile:../../../src/ip_cores/eth_ip/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0_in_context.xdc id:4 order:EARLY scoped_inst:network_interface_i/tri_mode_ethernet_mac_0_1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/bini/GARFIELD_MOBO/fifo_prj/fifo_prj.srcs/sources_1/ip/global_fifo/global_fifo/global_fifo_in_context.xdc rfile:../../../../fifo_prj/fifo_prj.srcs/sources_1/ip/global_fifo/global_fifo/global_fifo_in_context.xdc id:5 order:EARLY scoped_inst:network_interface_i/payload_1/ipbus_subsys_i/ipbus_merge/fifo_cntrl/global_fifo_inst} [current_design]
current_instance {network_interface_i/payload_1/ipbus_subsys_i/gen_dsp[0].dspiface/dsp_cntrl/channel_fifo_i}
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance rd_clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance wr_clk]
current_instance
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {network_interface_i/payload_1/ipbus_subsys_i/gen_dsp[0].dspiface/dsp_cntrl/channel_fifo_i}]
current_instance {network_interface_i/payload_1/ipbus_subsys_i/gen_dsp[1].dspiface/dsp_cntrl/channel_fifo_i}
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance rd_clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance wr_clk]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {network_interface_i/payload_1/ipbus_subsys_i/gen_dsp[1].dspiface/dsp_cntrl/channel_fifo_i}]
current_instance network_interface_i/mac_fifo_axi4_1
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance m_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance s_aclk]
current_instance
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells network_interface_i/mac_fifo_axi4_1]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name rgmii_rxc [get_ports rgmii_rxc]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name network_interface_i/tri_mode_ethernet_mac_0_1/rx_mac_aclk [get_pins network_interface_i/tri_mode_ethernet_mac_0_1/rx_mac_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name network_interface_i/tri_mode_ethernet_mac_0_1/tx_mac_aclk [get_pins network_interface_i/tri_mode_ethernet_mac_0_1/tx_mac_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name network_interface_i/tri_mode_ethernet_mac_0_1/rgmii_txc -source [get_pins network_interface_i/tri_mode_ethernet_mac_0_1/gtx_clk90] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins network_interface_i/tri_mode_ethernet_mac_0_1/rgmii_txc]
set_property src_info {type:SCOPED_XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports rgmii_rx_ctl]
set_property src_info {type:SCOPED_XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports rgmii_rx_ctl]
set_property src_info {type:SCOPED_XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports rgmii_rxc]
set_property src_info {type:SCOPED_XDC file:4 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports rgmii_rxc]
set_property src_info {type:SCOPED_XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {rgmii_rxd[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {rgmii_rxd[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {rgmii_rxd[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {rgmii_rxd[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {rgmii_rxd[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {rgmii_rxd[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {rgmii_rxd[3]}]
set_property src_info {type:SCOPED_XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {rgmii_rxd[3]}]
set_property src_info {type:SCOPED_XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports rgmii_tx_ctl]
set_property src_info {type:SCOPED_XDC file:4 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports rgmii_tx_ctl]
set_property src_info {type:SCOPED_XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports rgmii_txc]
set_property src_info {type:SCOPED_XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports rgmii_txc]
set_property src_info {type:SCOPED_XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {rgmii_txd[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {rgmii_txd[0]}]
set_property src_info {type:SCOPED_XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {rgmii_txd[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {rgmii_txd[1]}]
set_property src_info {type:SCOPED_XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {rgmii_txd[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {rgmii_txd[2]}]
set_property src_info {type:SCOPED_XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {rgmii_txd[3]}]
set_property src_info {type:SCOPED_XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {rgmii_txd[3]}]
current_instance network_interface_i/tri_mode_ethernet_mac_0_1
set_property src_info {type:SCOPED_XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 8 [get_ports -scoped_to_current_instance gtx_clk]
set_property src_info {type:SCOPED_XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 8 [get_ports -scoped_to_current_instance gtx_clk90]
set_property src_info {type:SCOPED_XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 8 [get_ports -scoped_to_current_instance tx_mac_aclk]
current_instance
set_property src_info {type:SCOPED_XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells network_interface_i/tri_mode_ethernet_mac_0_1]
current_instance network_interface_i/payload_1/ipbus_subsys_i/ipbus_merge/fifo_cntrl/global_fifo_inst
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance rd_clk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance wr_clk]
current_instance
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells network_interface_i/payload_1/ipbus_subsys_i/ipbus_merge/fifo_cntrl/global_fifo_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {network_interface_i/payload_1/ipbus_subsys_i/gen_dsp[0].dspiface/dsp_cntrl/channel_fifo_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {network_interface_i/payload_1/ipbus_subsys_i/gen_dsp[1].dspiface/dsp_cntrl/channel_fifo_i}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells network_interface_i/payload_1/ipbus_subsys_i/ipbus_merge/fifo_cntrl/global_fifo_inst]
